### ISSUE TITLE
package detection needs redesign and universality

### ISSUE THREAD

**Issue by deronnax** [ronnix/fabtools#252]
This issue (https://github.com/ronnix/fabtools/issues/217) enlightens a recurrent problem .
There is a big problem in `require` functions logic : there is no "universal" detection mechanism of installed package.

1. many assume the server is from debian-family : they just import require.deb (require.nginx.server, require.mysql.server,  require.apache.server)

2. the few other ones tediously import each package manager abstraction and test with each (require.supervisor.process)

An universal detection class is strongly lacking, to make such things possible:

``` python
Mysql
=====
def server():
    import require.package
    require.package("mysql")
```

Of course packages' names vary among Linux distribution, but many are the same (like uwsgi, supervisor, redis), and we could provide different package names to the function, e.g `require.package(deb='apache2', rpm='httpd')` ; and development package suffix  are easy to infer since there are convetions (-dev on Debian-like, -devel on RedHat like). This would be a huge gain to Fabtools. But it implies significant work and rewrite of parts.

Currently, due to the huge amount of require functions that just assume that the machine is a Debian-like, Fabtools is near to unusable on non debian target.

**Comment by ronnix** [comment]
Thanks for the feedback Matthieu. Closing this one as we already track OS-independent package installs in #167. Feel free to open issues for other specific bugs or enhancements.
