### ISSUE TITLE
Low level socket error connecting to host localhost on port 22: Connection refused

### ISSUE THREAD

**Issue by EmilTemirov** [ronnix/fabtools#278]
How I can use fabtools for local machine? I have written fabric command "setup_dev_environment":
```python
def setup_dev_environment():
    fabtools.deb.install([
        'libpq-dev',
        'libxslt-dev',
    ])
```
When I run *fab setup_dev_environment*, I get this error:
````
Fatal error: Low level socket error connecting to host localhost on port 22: Connection refused
````
What am I doing incorrectly?

**Comment by ronnix** [comment]
Fabric uses SSH to connect to the target machine. When the target machine is the local one, you need to have an SSH server running. If you're on OS X, go to System Preferences → Sharing and check "Remote Login" to enable SSH access.

**Comment by ronnix** [comment]
But based on your question, your development machine is Debian or Ubuntu, so SSH should be enabled. Maybe you have a firewall enabled?
